SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS DOWJONES_LIST;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE DOWJONES_LIST (
    SYMBOL VARCHAR(10) PRIMARY KEY, -- SYMBOL is the only column and also the primary key
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
