SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FILE_UPLOAD_HISTORY;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FILE_UPLOAD_HISTORY (
    ID VARCHAR(36) PRIMARY KEY,
    FILE_NAME VARCHAR(255) NOT NULL,
    UNIQUE_FILE_NAME VARCHAR(255) NOT NULL,
    UPLOADED_BY VARCHAR(100),
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FILE_URL VARCHAR(255) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL
);
