SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_EXCHANGE_INFO;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_EXCHANGE_INFO (
    EXCHANGE_SHORT_NAME VARCHAR(50),      -- Abbreviated name of the exchange
    EXCHANGE VARCHAR(255),         -- Full name of the exchange
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation timestamp
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (EXCHANGE_SHORT_NAME, EXCHANGE)
);


--INSERT INTO FMP_EXCHANGE_INFO (EXCHANGE_SHORT_NAME, EXCHANGE)
--SELECT DISTINCT 
--    EXCHANGE_SHORT_NAME,
--    EXCHANGE
--FROM 
--    FMP_STOCK_LIST
--ORDER BY 
--    EXCHANGE;
--
--COMMIT;