SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_HISTORICAL_DATA;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_HISTORICAL_DATA (
    SYMBOL VARCHAR(10) NOT NULL,
    DATE VARCHAR(10) NOT NULL,
    OPEN_PRICE DECIMAL(10, 2),
    HIGH_PRICE DECIMAL(10, 2),
    LOW_PRICE DECIMAL(10, 2),
    CLOSE_PRICE DECIMAL(10, 2),
    ADJ_CLOSE DECIMAL(10, 2),
    VOLUME BIGINT,
    UNADJUSTED_VOLUME BIGINT,
    PRICE_CHANGE DECIMAL(10, 2),
    CHANGE_PERCENT DECIMAL(10, 5),
    VWAP DECIMAL(10, 2),
    LABEL VARCHAR(20),
    CHANGE_OVER_TIME DECIMAL(10, 7),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SYMBOL, DATE)
);