SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_HISTORICAL_MARKET_CAP;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_HISTORICAL_MARKET_CAP (
    SYMBOL VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    MARKET_CAP BIGINT,
    PRIMARY KEY (SYMBOL, DATE)
);
