SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_STOCK_TYPE;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_STOCK_TYPE (
    TYPE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Record creation timestamp
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (TYPE)
);

--INSERT INTO FMP_STOCK_TYPE (TYPE)
--SELECT DISTINCT 
--    TYPE
--FROM 
--    FMP_STOCK_LIST
--ORDER BY 
--    TYPE;
--COMMIT;