SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_QUOTE_DATA;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_QUOTE_DATA (
    SYMBOL VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE DOUBLE,
    CHANGES_PERCENTAGE DOUBLE,
    CHANGE_VALUE DOUBLE,
    DAY_LOW DOUBLE,
    DAY_HIGH DOUBLE,
    YEAR_HIGH DOUBLE,
    YEAR_LOW DOUBLE,
    MARKET_CAP BIGINT,
    PRICE_AVG_50 DOUBLE,
    PRICE_AVG_200 DOUBLE,
    EXCHANGE VARCHAR(50),
    VOLUME BIGINT,
    AVG_VOLUME BIGINT,
    OPEN_PRICE DOUBLE,
    PREVIOUS_CLOSE DOUBLE,
    EPS DOUBLE,
    PE DOUBLE,
    EARNINGS_ANNOUNCEMENT TIMESTAMP,
    SHARES_OUTSTANDING BIGINT,
    TIMESTAMP BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 날짜
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 수정 날짜
);