SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_COMPANY_PROFILE;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_COMPANY_PROFILE (
    SYMBOL VARCHAR(50) PRIMARY KEY,
    PRICE DOUBLE,
    BETA DOUBLE,
    VOL_AVG BIGINT,
    MKT_CAP BIGINT,
    LAST_DIV DOUBLE,
    PRICE_RANGE VARCHAR(50),  -- Renamed from RANGE
    CHANGES DOUBLE,
    COMPANY_NAME VARCHAR(255),
    CURRENCY VARCHAR(10),
    CIK VARCHAR(20),
    ISIN VARCHAR(20),
    CUSIP VARCHAR(20),
    EXCHANGE VARCHAR(100),
    EXCHANGE_SHORT_NAME VARCHAR(50),
    INDUSTRY VARCHAR(100),
    WEBSITE VARCHAR(255),
    DESCRIPTION TEXT,
    CEO VARCHAR(100),
    SECTOR VARCHAR(50),
    COUNTRY VARCHAR(10),
    FULL_TIME_EMPLOYEES VARCHAR(50),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP VARCHAR(20),
    DCF_DIFF DOUBLE,
    DCF DOUBLE,
    IMAGE VARCHAR(255),
    IPO_DATE DATE,
    DEFAULT_IMAGE BOOLEAN,
    IS_ETF BOOLEAN,
    IS_ACTIVELY_TRADING BOOLEAN,
    IS_ADR BOOLEAN,
    IS_FUND BOOLEAN,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 날짜
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 수정 날짜
);
