SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS FMP_STOCK_LIST;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE FMP_STOCK_LIST (
    SYMBOL VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(255),
    EXCHANGE VARCHAR(255),
    EXCHANGE_SHORT_NAME VARCHAR(10),
    TYPE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 날짜
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 수정 날짜
);