SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS MENU_NAME;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE MENU_NAME (
    MENU_ID VARCHAR(50),              -- 메뉴 ID (MENU 테이블과 연결)
    LANG_CODE VARCHAR(10) NOT NULL, -- 언어 코드 (예: 'en' for English, 'ko' for Korean)
    MENU_NAME VARCHAR(255) NOT NULL,    -- 메뉴 이름
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 날짜
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  -- 수정 날짜
    PRIMARY KEY (MENU_ID, LANG_CODE) -- 메뉴 ID와 언어 코드로 복합 기본 키 설정    
);