SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS MENU;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE MENU (
    MENU_ID VARCHAR(50) PRIMARY KEY,  -- 문자열로 메뉴 ID 저장
    P_MENU_ID VARCHAR(50),            -- 부모 메뉴 ID (최상위 메뉴는 NULL)
    PATH VARCHAR(255),                -- 경로
    ORDER_NUM INT NOT NULL,           -- 메뉴 정렬 순서
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 날짜
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 수정 날짜
);