SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS POLYGON_GROUPED_DAILY_DATA;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE POLYGON_GROUPED_DAILY_DATA (
    TICKER VARCHAR(10) NOT NULL,
    TRADE_DATE VARCHAR(10) NOT NULL,
    CLOSE_PRICE DECIMAL(10, 4),
    HIGH_PRICE DECIMAL(10, 4),
    LOW_PRICE DECIMAL(10, 4),
    OPEN_PRICE DECIMAL(10, 4),
    NUMBER_OF_TRANSACTIONS INT,
    TRADING_VOLUME DECIMAL(20, 4),
    VOLUME_WEIGHTED_AVERAGE_PRICE DECIMAL(10, 4),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TICKER, TRADE_DATE)
);