SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS POLYGON_DAILY_OPEN_CLOSE;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE POLYGON_DAILY_OPEN_CLOSE (
    SYMBOL VARCHAR(10) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    AFTER_HOURS DECIMAL(10, 2),
    CLOSE_PRICE DECIMAL(10, 2),
    HIGH_PRICE DECIMAL(10, 2),
    LOW_PRICE DECIMAL(10, 2),
    OPEN_PRICE DECIMAL(10, 2),
    PRE_MARKET DECIMAL(10, 2),
    STATUS VARCHAR(10),
    VOLUME BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SYMBOL, TRADE_DATE)
);