SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ROLES;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE ROLES (
    ROLE_ID VARCHAR(50) PRIMARY KEY,  -- 권한 ID (VARCHAR로 변경)
    ROLE_NAME VARCHAR(50) NOT NULL,   -- 권한 이름 (예: admin, editor, viewer)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 시각
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 수정 시각
);