SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ROLE_MENU_PERMISSIONS;
SET FOREIGN_KEY_CHECKS = 1;

-- 테이블 생성
CREATE TABLE ROLE_MENU_PERMISSIONS (
    ROLE_ID VARCHAR(50),       -- 권한 ID (ROLES 테이블 참조, VARCHAR로 변경)
    MENU_ID VARCHAR(50),       -- 메뉴 ID (고유 메뉴 식별자)
    CAN_VIEW CHAR(1) DEFAULT 'N', -- 메뉴 조회 가능 여부 ('Y': 조회 가능, 'N': 조회 불가)
    CAN_EDIT CHAR(1) DEFAULT 'N', -- 메뉴 편집 가능 여부 ('Y': 편집 가능, 'N': 편집 불가)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 생성 시각
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  -- 수정 시각
    PRIMARY KEY (ROLE_ID, MENU_ID)
);