SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS RSI_HISTORY;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE RSI_HISTORY (
    SYMBOL VARCHAR(20),
    TRADE_DATE VARCHAR(10),  -- Format: YYYY-MM-DD
    RSI DOUBLE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SYMBOL, TRADE_DATE)
);
