SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS SCHEDULER_INFO;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE SCHEDULER_INFO (
    SCHEDULE_ID VARCHAR(255) NOT NULL,
	CLASS_NAME VARCHAR(255) NOT NULL,
    METHOD_NAME VARCHAR(255) NOT NULL,
    CRON_EXPRESSION VARCHAR(50) NOT NULL,
    ENABLED VARCHAR(1) DEFAULT 'N',
    DESCRIPTION VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SCHEDULE_ID)
);
