SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS STOCK_STATISTICS;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE STOCK_STATISTICS (
    SYMBOL VARCHAR(20) PRIMARY KEY,
    RSI DOUBLE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
