-- Add foreign key between ROLE_ID in ROLE_MENU_PERMISSIONS and ROLE_ID in ROLES table
ALTER TABLE ROLE_MENU_PERMISSIONS
ADD CONSTRAINT FK_ROLE_MENU_PERMISSIONS_ROLE
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
ON DELETE CASCADE;

-- Add foreign key between MENU_ID in ROLE_MENU_PERMISSIONS and MENU_ID in MENU table
ALTER TABLE ROLE_MENU_PERMISSIONS
ADD CONSTRAINT FK_ROLE_MENU_PERMISSIONS_MENU
FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
ON DELETE CASCADE;
