CREATE OR REPLACE VIEW V_MENUHIERARCHY AS
WITH RECURSIVE MENUHIERARCHY_CTE AS (
    SELECT 
        MENU_ID,
        P_MENU_ID,
        PATH,
        ORDER_NUM,
        1 AS LEVEL,
        CAST(LPAD(CAST(ORDER_NUM AS CHAR(255)), 10, '0') AS CHAR(1000)) AS SORT_ORDER
    FROM 
        MENU
    WHERE 
        P_MENU_ID IS NULL
    UNION ALL
    SELECT 
        M.MENU_ID,
        M.P_MENU_ID,
        M.PATH,
        M.ORDER_NUM,
        MH.LEVEL + 1 AS LEVEL,
        CAST(CONCAT(MH.SORT_ORDER, '.', LPAD(CAST(M.ORDER_NUM AS CHAR(255)), 10, '0')) AS CHAR(1000)) AS SORT_ORDER
    FROM 
        MENU M
    INNER JOIN 
        MENUHIERARCHY_CTE MH ON M.P_MENU_ID = MH.MENU_ID
)
SELECT 
    A.MENU_ID, 
    A.P_MENU_ID, 
    A.PATH, 
    A.ORDER_NUM, 
    A.LEVEL,
    A.SORT_ORDER,
    B.LANG_CODE,
    B.MENU_NAME 
FROM 
    MENUHIERARCHY_CTE A
LEFT JOIN MENU_NAME B ON A.MENU_ID = B.MENU_ID;